### ISSUE TITLE
Deprecate `get client`; openshift-python-wrapper.get_client should be used - 340

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/openshift-python-utilities#341]
[Auto generated]
Number: [#340]

**Comment by msi-b1** [comment]
[1;34mopenshift-python-utilities[1;0m(4QCFR)[PR 340]: Closing issue for PR: Deprecate `get client`; openshift-python-wrapper.get_client should be used.
PR was closed.
